news_sites:
  0:
    url: https://www.vanguardia.com
    categories_links: '//div[@class="nav-dropdown nav noSubNav"]/ul/li/a[@class="tab-item lnk"]/@href'
    categories_text: '//div[@class="nav-dropdown nav noSubNav"]/ul/li/a[@class="tab-item lnk"]/span[@class="sectionName"]/text()'
    articles: '//article/div/a/@href'
    queries:
      title: '//div[@class="template-vg-17"]/h1[@itemprop="headline"]/span[@class="priority-content"]/text()'
      subtitle: '//div[@class="template-vg-17"]/div[@class="subheadline font-1 bold lead"]/text()'
      content: '//div[@class="paragraph"]//p/text()'
      images: '//figure[@class="cutlineShow"]/div/img/@data-srcset'
      category_long: '//*[@id="r00-c00"]/div[4]/ol/li[last()]/a/span/text()'
      tags: '//section[@class="categoryList"]/article/a/span/text()'
      author: '//div[@itemprop="author"]/a/text()'
      publication_date: '//div[@class="template-vg-17"]/div[@class="date font-1"]/@content'
      categories: '//*[@id="r00-c00"]/div[4]/ol/li/a/span/text()'
      